In [42]:
import pandas as pd
import numpy as np
np.empty(5) # одномерный массив из пяти элементов, память для которого выделена, но не инициализирована
np.zeros((10, 7)) # массив размером 10x7, заполненный нулями 
np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами 
np.eye(3) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3
np.full((3, 5), 3.14)  # массив 3x5 заполненный числом 3.14
np.arange(0, 21, 7)  # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7
np.linspace(0, 1, 5)  # массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно
np.random.randint(0, 10, (3, 3))  # массив размера 3х3, заполненный случайными числами из диапазона от 0 до 9 (включительно)

array([[8, 3, 6],
       [7, 6, 4],
       [6, 8, 0]])

In [43]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [46]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
np.random.randint(0, 5, 3)

array([3, 1, 3])

In [60]:
my_array = np.array([x for x in range(10)])
my_array[-9:6:2] # в общем всё как со списками

array([1, 3, 5])

In [82]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])
display(my_array)
my_array[0][2] # то же самое что и my_array[0,2]
my_array[:,2] # весь 3 столбец
my_array[:2,3] # 4 столбец 1,2 строк 
my_array[:2,0] # 1 столбец 1,2 строк
my_array[1:] # 2,3 строки
my_array[1:,1:3] #2 и 3 элементы 2 и 3 строки

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13],
       [45, 46, 47, 48]])

array([ 1, 10])

In [290]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])
display(big_secret)

array([[1.40000000e+01, 1.00000000e+01, 6.00000000e+00, 5.60000000e+01,
        4.00000000e+01, 2.40000000e+01, 9.80000000e+01, 7.00000000e+01,
        4.20000000e+01, 1.40000000e+02, 1.00000000e+02, 6.00000000e+01,
        1.82000000e+02, 1.30000000e+02, 7.80000000e+01, 2.24000000e+02,
        1.60000000e+02, 9.60000000e+01, 2.66000000e+02, 1.90000000e+02,
        1.14000000e+02, 3.08000000e+02, 2.20000000e+02, 1.32000000e+02,
        3.50000000e+02, 2.50000000e+02, 1.50000000e+02, 3.92000000e+02,
        2.80000000e+02, 1.68000000e+02, 4.34000000e+02, 3.10000000e+02,
        1.86000000e+02, 4.76000000e+02, 3.40000000e+02, 2.04000000e+02,
        5.18000000e+02, 3.70000000e+02, 2.22000000e+02, 5.60000000e+02,
        4.00000000e+02, 2.40000000e+02, 6.02000000e+02, 4.30000000e+02,
        2.58000000e+02, 6.44000000e+02, 4.60000000e+02, 2.76000000e+02,
        6.86000000e+02, 4.90000000e+02, 2.94000000e+02],
       [3.16227766e+01, 3.16543836e+01, 3.16859590e+01, 3.17175031e+01,
       

In [113]:
round(sum(list(big_secret[:,-1])),2)

3154.33

In [124]:
small_secret = big_secret[:,:5]
display(small_secret)
diagonal_sum = sum(small_secret[i,i] for i in range(len(small_secret)))
round(diagonal_sum,2)

array([[14.        , 10.        ,  6.        , 56.        , 40.        ],
       [31.6227766 , 31.65438358, 31.68595904, 31.71750305, 31.74901573],
       [ 0.        ,  1.        ,  4.        ,  9.        , 16.        ],
       [31.6227766 , 31.65438358, 31.68595904, 31.71750305, 31.74901573],
       [14.        , 10.        ,  6.        , 56.        , 40.        ]])

121.37

In [163]:
small_secret2 = big_secret[:,-5:]
display(small_secret2)
diagonal = list(small_secret2[i,i] for i in range(len(small_secret2)))

def multip(x):
    result = 1
    for i in x:
        result = i * result
    return result

multip(diagonal)

array([[ 460.        ,  276.        ,  686.        ,  490.        ,
         294.        ],
       [  33.04542328,   33.07567082,   33.10589071,   33.13608305,
          33.1662479 ],
       [2116.        , 2209.        , 2304.        , 2401.        ,
        2500.        ],
       [  33.04542328,   33.07567082,   33.10589071,   33.13608305,
          33.1662479 ],
       [ 460.        ,  276.        ,  686.        ,  490.        ,
         294.        ]])

341505315559.2347

In [304]:
'''Продолжим работать с массивом big_secret. Замените на 1 все элементы, 
у которых оба индекса нечётные, и на -1 все элементы, у которых оба индекса чётные.'''
big_secret[::2,::2] = -1
big_secret[1::2, 1::2] = 1
display(big_secret)

''' Выделите из каждой строки обновлённого массива big_secret первые 5 элементов. 
Чему равна сумма элементов главной диагонали получившейся матрицы? 
Введите полученный ответ без изменений и округлений.'''

new_slice = big_secret[:,:5]
new_slice_sum = sum(new_slice[i][i] for i in range(len(new_slice)))
new_slice_sum

'''Выделите из каждой строки обновлённого массива big_secret последние 5 элементов. 
Чему равно произведение элементов главной диагонали получившейся матрицы? Введите полученный результат без изменений и округлений.
'''

new_slice2 = big_secret[:,-5:] 
new_slice2_diagonal = list(new_slice2[i][i] for i in range(len(new_slice2)))
multip(new_slice2_diagonal)

array([[-1.00000000e+00,  1.00000000e+01, -1.00000000e+00,
         5.60000000e+01, -1.00000000e+00,  2.40000000e+01,
        -1.00000000e+00,  7.00000000e+01, -1.00000000e+00,
         1.40000000e+02, -1.00000000e+00,  6.00000000e+01,
        -1.00000000e+00,  1.30000000e+02, -1.00000000e+00,
         2.24000000e+02, -1.00000000e+00,  9.60000000e+01,
        -1.00000000e+00,  1.90000000e+02, -1.00000000e+00,
         3.08000000e+02, -1.00000000e+00,  1.32000000e+02,
        -1.00000000e+00,  2.50000000e+02, -1.00000000e+00,
         3.92000000e+02, -1.00000000e+00,  1.68000000e+02,
        -1.00000000e+00,  3.10000000e+02, -1.00000000e+00,
         4.76000000e+02, -1.00000000e+00,  2.04000000e+02,
        -1.00000000e+00,  3.70000000e+02, -1.00000000e+00,
         5.60000000e+02, -1.00000000e+00,  2.40000000e+02,
        -1.00000000e+00,  4.30000000e+02, -1.00000000e+00,
         6.44000000e+02, -1.00000000e+00,  2.76000000e+02,
        -1.00000000e+00,  4.90000000e+02, -1.00000000e+0

-1.0

In [305]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число: {}'.format(result1, result2, result3, result4, result5))

Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


In [311]:
my_array = np.random.randint(0, 10, (3,4))
my_array

array([[7, 6, 6, 8],
       [3, 0, 5, 6],
       [2, 3, 3, 3]])

In [312]:
my_array<5

array([[False, False, False, False],
       [ True,  True, False, False],
       [ True,  True,  True,  True]])

In [313]:
my_array[my_array<5]

array([3, 0, 2, 3, 3, 3])

In [314]:
mask = np.array([1, 0, 1, 0], dtype=bool)
my_array[:, mask]

array([[7, 6],
       [3, 5],
       [2, 3]])

In [316]:
my_array[:,np.array([1,0,1,0],dtype=bool)]

array([[7, 6],
       [3, 5],
       [2, 3]])

In [318]:
my_array = np.random.randint(1,100,(5,5))
my_array

array([[71, 65,  9, 29, 17],
       [56, 92, 96, 74, 98],
       [ 2, 97, 70,  2, 50],
       [48, 38, 58, 65,  6],
       [88, 11, 12, 69, 12]])

In [319]:
np.sort(my_array,axis=1)

array([[ 9, 17, 29, 65, 71],
       [56, 74, 92, 96, 98],
       [ 2,  2, 50, 70, 97],
       [ 6, 38, 48, 58, 65],
       [11, 12, 12, 69, 88]])

In [322]:
np.sort(my_array,axis=0)

array([[ 2, 11,  9,  2,  6],
       [48, 38, 12, 29, 12],
       [56, 65, 58, 65, 17],
       [71, 92, 70, 69, 50],
       [88, 97, 96, 74, 98]])

In [359]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T
display(sum(np.cos(great_secret[0]))) #1
display(sum(great_secret[great_secret>50])) #2
display(great_secret.flatten()[150]) #3
display(sum((np.sort(great_secret,axis=0))[-1])) #4
#display(great_secret)

0.16006721889793019

5470.0

7.0710678118654755

115.12148016521353

[0.0,
 1.0,
 1.4142135623730951,
 1.7320508075688772,
 2.0,
 2.23606797749979,
 2.449489742783178,
 2.6457513110645907,
 2.8284271247461903,
 3.0,
 3.1622776601683795,
 3.3166247903554,
 3.4641016151377544,
 3.605551275463989,
 3.7416573867739413,
 3.872983346207417,
 4.0,
 4.123105625617661,
 4.242640687119285,
 4.358898943540674,
 4.47213595499958,
 4.58257569495584,
 4.69041575982343,
 4.795831523312719,
 4.898979485566356,
 5.0,
 5.0990195135927845,
 5.196152422706632,
 5.291502622129181,
 5.385164807134504,
 5.477225575051661,
 5.5677643628300215,
 5.656854249492381,
 5.744562646538029,
 5.830951894845301,
 5.916079783099616,
 6.0,
 6.082762530298219,
 6.164414002968976,
 6.244997998398398,
 6.324555320336759,
 6.4031242374328485,
 6.48074069840786,
 6.557438524302,
 6.6332495807108,
 6.708203932499369,
 6.782329983125268,
 6.855654600401044,
 6.928203230275509,
 7.0,
 7.0710678118654755,
 7.14142842854285,
 7.211102550927978,
 7.280109889280518,
 7.3484692283495345,
 7.4161984870

In [373]:
first = [1,2,3,4,5,6,7,8,9,10]
second = [135,160,163,147,138,149,136,154,137,165]
third = [34,43,40,44,41,54,39,48,35,60]
forth = [4,5,4.3,5,4.7,3.9,4.2,4.9,3.7,4.6]
students = np.array([first,second,third,forth])
students = students.T
students

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])

In [381]:
mean = np.mean(students[:,-1])
display(mean)
median = np.median(students[:,-1])
display(median)
sort = np.sort(students[:,-1]) # посчитаем медиану другим способом
display((sort[4] + sort[5])/2)


4.430000000000001

4.449999999999999

4.449999999999999

In [384]:
mass_median = np.median(students[:,-2])
mass_median

42.0

In [385]:
np.mean(students[:,-2]) - np.median(students[:,-2])

1.7999999999999972

In [390]:
corr = np.corrcoef(students[:,1], students[:,2])
corr

array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

In [393]:
corr1 = np.corrcoef(students[:,2],students[:,-1])
corr1

array([[1.        , 0.29801325],
       [0.29801325, 1.        ]])

In [395]:
students_height_std = np.std(students[:,1])
students_height_std

11.083320801997928

In [399]:
students_grades_std = np.std(students[:,-1])
students_grades_std

In [400]:
dispersion

0.2041

In [402]:
students_weight_std = np.std(students[:,-2])
weight_dispersion = students_weight_std**2
weight_dispersion

60.36

In [427]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])
my_slice = my_array[1:4,1:4]
my_slice

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [430]:
my_sin = np.sin(my_array)
my_sin_sum = np.sum(my_sin)
my_sin_sum

-0.05812430261413351

In [435]:
my_sin[1:4,1:4] = 1
np.sum(my_sin)

7.571718421269144

In [442]:
np.sum((my_sin[:,:4].reshape(10,2))[:,0])

2.4057172058139544

In [449]:
big_data = np.array([x**2 for x in range(100,1001) if x%2 == 1])

In [451]:
np.median(big_data)

302501.0

In [456]:
np.std(big_data)
big_data

array([ 10201,  10609,  11025,  11449,  11881,  12321,  12769,  13225,
        13689,  14161,  14641,  15129,  15625,  16129,  16641,  17161,
        17689,  18225,  18769,  19321,  19881,  20449,  21025,  21609,
        22201,  22801,  23409,  24025,  24649,  25281,  25921,  26569,
        27225,  27889,  28561,  29241,  29929,  30625,  31329,  32041,
        32761,  33489,  34225,  34969,  35721,  36481,  37249,  38025,
        38809,  39601,  40401,  41209,  42025,  42849,  43681,  44521,
        45369,  46225,  47089,  47961,  48841,  49729,  50625,  51529,
        52441,  53361,  54289,  55225,  56169,  57121,  58081,  59049,
        60025,  61009,  62001,  63001,  64009,  65025,  66049,  67081,
        68121,  69169,  70225,  71289,  72361,  73441,  74529,  75625,
        76729,  77841,  78961,  80089,  81225,  82369,  83521,  84681,
        85849,  87025,  88209,  89401,  90601,  91809,  93025,  94249,
        95481,  96721,  97969,  99225, 100489, 101761, 103041, 104329,
      

In [462]:
np.corrcoef(big_data[::2],big_data[1::2])

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])